---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.min.io
      chart: minio
      version: 3.4.6
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2022-01-08T03-11-54Z
    env:
      TZ: "Europe/Stockholm"
    rootUser: {SECRET_USER_MINIO}
    rootPassword: {SECRET_PASS_MINIO}

    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_ADDR}"
            path: /srv/nfs/minio/.minio
        mountPath: /root/.minio
      data:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_ADDR}"
            path: /srv/nfs/minio
        mountPath: /data

    service:
      main:
        enabled: true
        type: LoadBalancer
        ports:
          http:
            port: 9001
          api:
            port: 9000
        externalTrafficPolicy: Local

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/name: "minio"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-download"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "minio.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9001
        tls:
          - hosts:
              - "minio.${SECRET_DOMAIN}"
            secretName: "minio-tls"
      s3:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/name: "s3"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-download"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "s3.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9000
        tls:
          - hosts:
              - "s3.${SECRET_DOMAIN}"
            secretName: "s3-tls"

    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
