---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://library-charts.k8s-at-home.com
      chart: common
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-library-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2022-01-08T03-11-54Z
    env:
      TZ: "Europe/Stockholm"
      MINIO_ROOT_USER: {SECRET_USER_MINIO}
      MINIO_ROOT_PASSWORD: {SECRET_PASS_MINIO}
    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_ADDR}"
            path: /srv/nfs/minio/.minio
        mountPath: /root/.minio
      data:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_ADDR}"
            path: /srv/nfs/minio
        mountPath: /data
    args:
      - server
      - /data
      - --console-address
      - :9001
    service:
      main:
        ports:
          http:
            enabled: true
            port: 9001
          api:
            enabled: true
            port: 9000
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "minio.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9001
          - host: "s3.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9000
        tls:
          - hosts:
              - "minio.${SECRET_DOMAIN}"
              - "s3.${SECRET_DOMAIN}"
            secretName: "minio-tls"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
