---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 2.9.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/loki
    ingress:
      enabled: false
#      annotations:
#        kubernetes.io/ingress.class: traefik
#        cert-manager.io/cluster-issuer: "letsencrypt-production"
#        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
#      hosts:
#        - host: &host "loki.${SECRET_DOMAIN}"
#          paths:
#            - /
#      tls:
#        - secretName: "loki-tls"
#          hosts:
#            - *host
    config:
      storage_config:
        aws:
          bucketnames: loki
          endpoint: "s3.${SECRET_PRIVATE_DOMAIN}"
          access_key_id: "${SECRET_ACCESS_MINIO}"
          secret_access_key: "${SECRET_KEY_MINIO}"
          s3forcepathstyle: true
          insecure: false
        boltdb_shipper:
          active_index_directory: /data/loki/index
          cache_location: /data/loki/index_cache
          resync_interval: 5s
          shared_store: s3
      ruler:
        enabled: false
    persistence:
      enabled: false
    serviceMonitor:
      enabled: true
