apiVersion: v1
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:wQdJGbwo2FBS1NDdsZCxu10jmxGTBbKUu4RmbDWNENtw0AFB7K3f9TbG06iEPg92gmmVwzaOMnuK9rRzL10AdLVvdIvAbLmoT/hAAPwhPJBgcCjSymkw/u1+0QpcHANMPMHgg4904hP4sj56SX5vzlLB2mrzMdnj0XYFYzCACg0ZiMgZSjqCQtOtnAqQhzWRBleZ,iv:g/RnuH3MK/ERYUcKAykN7o4oebNQ4GeTwEC+FLrQyUg=,tag:bWle8oFZ1LYNJeSHR2YMiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sv3k3xpc3r8glku67cew5cv787ly3zw4trx4dakduzvdus5st9xsc8apkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRUd6WUE0ZE1PYmNMcmt5
            aGNaSDMvUjZiZ2JCcWZmVWFOenFRWTBQZlVzCk9pejY3MUM2Q0VTaHk2TWhYcnZr
            NE1ocEFCRlkvRVVDemRzWWd2T2hESXMKLS0tIG90b201WGp2MHpXVW95M3FJMXVL
            SGp0K2VUU1VJUHoxbFd6aUN4dCtzZ2cKfkokx+NCDSZWnsjJgdjP25Wt+dCWSMJn
            Azn5eno+vQUmFaL0dbODrgW1vExU9kRYCu0pTx9rDik4dlry3f8v/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-24T18:40:56Z"
    mac: ENC[AES256_GCM,data:qNoy5ComKf/bZ6mrTvAPUz9K1z9Y/R5QYjHI4MXM7cfNyHp1F1fw8OLY828xkgqQF3MymmDjIza+IeM6GqdE+kt7uClmtjE044ypjG2f8hArSfZzlE9EiAMjuSOBZ81Nsid0OigQlquZAsK16qAIv5KeGTlJb9kC3/h58KBLAvc=,iv:ZKrV5MJGyFgfrzkVVDNBXPKKEVCLUchBECBG+0JnjiQ=,tag:0XsbzfY8OqoRHEzv8ATYTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
