---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent-novpn
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 13.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.4.0
    env:
      TZ: "Europe/Stockholm"
      WAIT_FOR_VPN: "true"
    hostname: qbittorrent
    service:
      bittorrent:
        enabled: true
        type: LoadBalancer
        ports:
          bittorrent:
            port: 50413
            name: bittorrent
            protocol: TCP
            targetPort: 6881
        externalTrafficPolicy: Local

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/name: "qBittorrent novpn"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-download"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "torrent2.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "torrent2.${SECRET_DOMAIN}"
            secretName: "torrent2-tls"
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-novpn-config
      torrents:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_ADDR}"
            path: /srv/nfs/torrents
        mountPath: /torrents
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_ADDR}"
            path: /srv/nfs/media
        mountPath: /media
      shared:
        enabled: true
        type: emptyDir
        mountPath: /shared
    addons:
      vpn:
        enabled: false
    resources:
      requests:
        memory: 250Mi
        cpu: 400m
      limits:
        memory: 4000Mi
