---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: vaultwarden
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: vaultwarden/server
      tag: 1.32.2
    env:
      DOMAIN: https://vaultwarden.${SECRET_DOMAIN}
      SIGNUPS_ALLOWED: false
      WEBSOCKET_ENABLED: true
      ADMIN_TOKEN: ${SECRET_TOKEN_VAULTWARDEN}
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "shield-lock"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns.alpha.kubernetes.io/target: "ext.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: &host "vaultwarden.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
              - path: /notifications/hub/negotiate
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "vaultwarden-tls"
      admin:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: *host
            paths:
              - path: /admin
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "vaultwarden-tls"
    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config
