---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi
      version: 4.7.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: Europe/Stockholm
      UNIFI_GID: 1000
      UNIFI_UID: 1000
    image:
      repository: jacobalberty/unifi
      tag: v7.0.25
    service:
      main:
        type: LoadBalancer
        annotations:
          coredns.io/hostname: unifi
        loadBalancerIP: ${LB_UNIFI}
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: &host "unifi.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "unifi-tls"
    persistence:
      data:
        enabled: true
        existingClaim: unifi-config
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        memory: 2048Mi
