---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k10-backups
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 128Mi
