---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overserr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 256Mi
