---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-ceph
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 768Mi
