# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:799X9X5N4uKWT4w=,iv:+Vko4DqmztBOz1k6kOhi8uEFueilzSzMRtaCQ0CYAnQ=,tag:LAC1ehJKQm1g+5YjjHZJ6Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:tnP5NlrZ7Z4zdmFXE8V9o6uC1vbhRw==,iv:nMpDPu32V3foQRKagvE/sSnC/9GnMlqlMheMzB6KDs8=,tag:eEffHv0x56K2GQhEmPhyrQ==,type:str]
    SECRET_PASS_GRAFANA: ENC[AES256_GCM,data:H6QgPiyZhkwkixo8FdpzN86Cpp8=,iv:rnXZTDHbM2OVHTjiaQxhr+O8f1X4VK0KK5+aXnUrOfI=,tag:oJ9l7JwuPoCZsDR0wfIwRg==,type:str]
    SECRET_USER_MINIO: ENC[AES256_GCM,data:HGakuead/TOveDxX+n7SGQ==,iv:Z07W/sGXbxmjXUiEzftWsqJ1yi/wBp2xRoVXyAcA8G4=,tag:NgtJBZHhozZIacrSJtJiIg==,type:str]
    SECRET_PASS_MINIO: ENC[AES256_GCM,data:Fjdu7ChJlhnQWVKQBzZ1bQ==,iv:ze+rASomeDVVF4+LuVgfbLNC31VYzvhOPCdBLrZMxl4=,tag:7VQ0JGVYwc7trQBkZ1LmDA==,type:str]
    SECRET_ACCESS_MINIO: ENC[AES256_GCM,data:D0E4TvS9l6MWQEOj7e7cOQ==,iv:dB+j5mZpBNPTaK6vOhXkGZSWuJcCWHOAev2AKO55GXw=,tag:SWFjd40CjSTyEIeRLGF7Ng==,type:str]
    SECRET_KEY_MINIO: ENC[AES256_GCM,data:qL/wMzcMOCavDP7Uw13w8w==,iv:0KC8kgI+mDKdyAcLmu1aOpXusEZUffLnZAdjBOsbGJg=,tag:58F8shL8myl3v/NSHvFs1g==,type:str]
    SECRET_TOKEN_VAULTWARDEN: ENC[AES256_GCM,data:8iNSLenyMDJvQg/8mZsXrA==,iv:lpOVArSDwUVv7oS/FveaU24ePcuzUtNtfTMb9bdoWAk=,tag:s5hIZV649ZRyO1assAFuEA==,type:str]
    SECRET_ALERTMANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:sJSAr0fxCX1w/gvZn9gaOp+oi+pyjpI0NHTRI3Q5RDXOLaTU8BeK3HKh4NYPc4xl6bmrEnrC9kq9xtBCkEUrdomJYMvFweLMCNDWhd7PKH1uJkKyOEJna8kLY9R9my9jyYxFfqwhrvAjiSteeDo0Sg3gK28BmD+lC4yf91zj,iv:fbfUTefr2WulBYujDOcR57aLpGh2SxbDYHT6Q3k4v48=,tag:GN34onni0d/nbWtgqSLelg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sv3k3xpc3r8glku67cew5cv787ly3zw4trx4dakduzvdus5st9xsc8apkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHb2xhR0NFZ3BETHI1TGdT
            SjR6TVlGZnRqYWtPQkJ1K3UyeEtiSlIvYm1nCjJCL0puOTBEQkNJdUUwdTNxenFk
            RjNRTnJLS2JiQi9GMkgwYm1tbExZdlkKLS0tIE9sU1JOc3FCY0VGMTMremhUcXlW
            dUtmcnlhMmg1MnI5clFUK0VrSGtlR2MKgXCCOrGP4rFaSIkiUoc041q+O89zCDNL
            tjrvF1A0IHxquSlZGC63dMjV5Ook37g0Le2U/t0ClPW659CaNqKPgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-04T12:58:16Z"
    mac: ENC[AES256_GCM,data:0XJIx8vy9T1PvQUp8TDDvXFwa/H+XEeeFR7mTGYUOeAIpK+Wy03wth/BEe5I7jWyMYsdfZJe/OPUP/JULOY4IM8eBNkqvLoOm1C038caxXmGhlL0DM+pYb/2xKwR+17yAACrBwiHF/TRvuW11Gltoh/+90AKr2U/LbzFJPkGACY=,iv:nOFe3NEbTcAKWvRmUhFX1LmdOmcqLETE8oMdenrPu3E=,tag:rfIwbc4GyhWBiDGXkZSm8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
