---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-iscsi
  namespace: kube-system
spec:
  releaseName: democratic-iscsi
  interval: 5m
  chart:
    spec:
      chart: democratic-csi
      version: 0.6.3
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-charts
        namespace: flux-system
      interval: 5m
  values:
    csiDriver:
      name: "org.democratic-csi.iscsi"
    storageClasses:
    - name: zfs-generic-iscsi-csi
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: ext4
      mountOptions: []
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:
    driver:
      config:
        driver: zfs-generic-iscsi
        iscsi:
          targetPortal: "10.0.10.10:3260"
          shareStrategyTargetCli:
            basename: "iqn.2022-02.${SECRET_DOMAIN}"
