apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - kube-system
  - networking
  - system-upgrade
  - media
  - monitoring
  - kasten-io
  - vpn-gateway
  - rook-ceph
