# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:ZR9zswBk1WX2BK7BoAUzgUMUI1bOruSjBQOiRjQYCn/ZJ9DERA==,iv:m34fpYY8O/f4G+258IPqzi6Q4bQ22tAZYfYHZDHFDq4=,tag:nArcEvlcKMwhZhjvU5q8CA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sv3k3xpc3r8glku67cew5cv787ly3zw4trx4dakduzvdus5st9xsc8apkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdjFPZkNOODJJNlBpQWdo
            Y3llalI2UkZmNjRST3RWamFPZDdlZ1R2SEhFCmU3M3RzcWhuU1kwajAzOG1HQlVr
            NExYZmYrSlBRcEVpNjhaUFpSSnppbk0KLS0tIHhTamw3cHdWa3hvN1UzRGVjZDg1
            aXdiWjlzVFEvTzFhY2w5WVNnMkZhWW8KpNqqkYjPsM/5g0Jz+Q0pi7Z6/Hu0NtZc
            8QrdYVX/ykPtP8MgOiJBmFfc3p5noabR+zTsbLpNbXsSQRN+7xxBJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-28T16:13:19Z"
    mac: ENC[AES256_GCM,data:XS/jNE38GVRQb+iY/dRWrNErpyZxAsJoMcWGwfh9aI0jmYSfgr3TtI08Dj6+4JCZaxUtEeiP/fvLxwVk1dc4BV4HJ4o+GCoWf/U8nwWCvi3EzucmckQqZN2gAjSTj+rQtyMrxZSUGNQrYGrt2EMyvw9HAeVl4PUlMvaYHiSj0iY=,iv:mffZflJbTQBk3ktWkk8v/pIPvF9CNskWts9W0JFIBaE=,tag:4DvvKY/UAcoYeUDCo6k3rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
