# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:sTlm5i5if1jXFRPb1s0vMPX7oq6CgPXPtzPmmeEp69G1Xmt7sOBXdQ==,iv:WrvKFSCQ5oXEyOlTh2GSnSVYA6zAoTcwItU3JEBynyg=,tag:FkX8zjGCkAodD1jkY2QhOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sv3k3xpc3r8glku67cew5cv787ly3zw4trx4dakduzvdus5st9xsc8apkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqK0ZSdWlTU09nRlpGQW51
            eFdmSXh4ZUJWaEtLbFZmQWovQk9MMXh4UlE4CjJqQUFwYnhQb1hZSjJEWW5rZ3ZJ
            VTFCY0JySlMzLzVrOHkvRXhhTHlYeW8KLS0tIEw0RFV4Sm1ybTA1VDNFVldOWERE
            alBqQVk1YkZFQTdneE9WSGFEYU9oTFEKAOmccB9Lo4loXC8rhzGuDaJrFktENpGw
            tR1Y/IxOM83uupA5ifxZ1mjMbiWsqONhphAMPvWKSjdMaXlHDFL72A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-28T13:55:24Z"
    mac: ENC[AES256_GCM,data:bERGzMV1d7h68tpaNl2q33oi0mU8CKiZi3UiwEp5Dld5bB5pwEtuY8q3lNR5H0P8Gls96QdDwG9LDFaWOXHGQCZRUlNgX1JeBFEOkdusKDik8LInG7fMUPZGAYiNZqbExjOAEGN8e42y1N5dWLwYLzYSxi1eY5BvW8biQt3q0xY=,iv:l6ukduAn98Rhwwu6gklNHxFc/WgEIsw6Z/k/jW4ij/I=,tag:wiqhqOHQNxRD6ae26S/7uQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
