---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: readarr
      version: 6.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/readarr
      tag: v0.1.1.1352
    env:
      TZ: "Europe/Stockholm"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "book-music"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: &host "readarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "readarr-tls"
    persistence:
      config:
        enabled: true
        existingClaim: readarr-config
      torrents:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_ADDR}"
            path: /srv/nfs/torrents
        mountPath: /torrents
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_ADDR}"
            path: /srv/nfs/media
        mountPath: /media
    probes:
      liveness:
        custom: false
        spec:
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 10
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
