---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  interval: 5m
  chart:
    spec:
      chart: k10
      version: 4.5.9
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 5m
  values:
    eula:
      accept: true
      company: onedr0p
      email: onedr0p@@users.noreply.github.com
    global:
      persistence:
        storageClass: ceph-block
    clusterName: k8s
    grafana:
      enabled: false
    ingress:
      create: true
      class: traefik
      host: "k10.${SECRET_DOMAIN}"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      urlPath: k10
      hosts:
        - k10.${SECRET_DOMAIN}
      tls:
        enabled: true
        secretName: k10-tls
